# Generated by Django 2.2.16 on 2022-06-03 07:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220603_0721'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='restrict_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='prevent_self_follow'),
        ),
    ]
